
import './PPCServices.css'

const PPCServices = () => {
  return (
    <section>
        <div className="container pServices__container">
            <div className="pService__left">
                <h1 className="heading">Substantially increase your ROI with PPC Services</h1>

                <p className="card__des">According to Google, businesses typically earn $2 for every $1 spent on Google Ads. The returns generated by Comrade clients are even better, yielding $10 for every $1 invested. Our high-performance websites and advertising campaigns work together to deliver unparalleled returns on investment for our clients, increasing their revenue in measurable ways.</p>
            </div>
            <div className="pService__right">
                <img src="https://comradeweb.com/wp-content/webp-express/webp-images/doc-root/wp-content/uploads/2022/03/shutterstock_1832160472-1.jpg.webp" alt="" className='main' />

                <img src="https://comradeweb.com/wp-content/webp-express/webp-images/doc-root/wp-content/uploads/2022/03/Facebook_icon.png.webp" alt="" className="top" />

                <img src="https://comradeweb.com/wp-content/webp-express/webp-images/doc-root/wp-content/uploads/2022/03/waves.png.webp" alt="" className="right" />

                <img src="https://comradeweb.com/wp-content/webp-express/webp-images/doc-root/wp-content/uploads/2022/03/results.png.webp" alt="" className="left" />
            </div>
        </div>
    </section>
  )
}

export default PPCServices